### ISSUE TITLE
Double Counting of Green Roof Drainage Mat Final and Initial Volume

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/Stormwater-Management-Model#102]
As discussed on OpenSWMM.ORG https://www.openswmm.org/Topic/32892/initial-storage-by-lid-summary-results  the three layer Green Roof of SWMM5 seems to count the volume in the lower layer or Drainage Mat Twice.  

In the attached file the drainage mat is 100 mm, the void fraction is 0.5 and the percent saturated is 50 percent.  The initial storage should be 100 * 0.5  * 0.5 or 25 mm.  It is listed as 50 mm as the storage depth is set equal to drainage mat depth as explained on OpenSWMM  

[SWMM_Erica Orsi.inp.txt](https://github.com/USEPA/Stormwater-Management-Model/files/10252824/SWMM_Erica.Orsi.inp.txt)

the value for initial and final storage of the Green Roof should not include the Drainage Mat twice.

**Comment by michaeltryby** [comment]
Closed in Release v5.2.3
