### ISSUE TITLE
node depth data in .hsf file does not match with the simulation result

### ISSUE THREAD

**Issue by Yunp-J** [USEPA/Stormwater-Management-Model#108]
Hi, im using python to read the data in .hsf file and focus on the node depth feature.    I executed a simulation and generated a hot start file by swmm, and then read the node depth of the generated hsf file. However, I just found that the node depth unpacked from the hsf file is different from the simulation result.    It seems that the data in the .hsf file is larger than it in the simulation result.

So my question is: does the hot start file save the simulated node depth or save it with some certain format?

**Comment by dickinsonre** [comment]
The formatting of the numbers in the hsf file are defined in hotstart.c.  How are you determining the ending simulation value - is it from the output tables of SWMM?  If you do not save the hsf file at the same time as the report time step they may be reported or saved at different times.

**Comment by cbuahin** [comment]
@Yunp-J, another thing to consider is that node depth is saved using a floating point in the hotstart file. If you are using an incorrect byte size allocation in python that may lead to mismatches as well. I am going to go ahead and close this issue if you can confirm you have been able to address it.
