### ISSUE TITLE
Computing equivalent slope incorrectly for curb inlets on grade

### ISSUE THREAD

**Issue by BenTWhite** [USEPA/Stormwater-Management-Model#110]
On line 1494 of inlet.c you have:
Se = Sx + Sw * Eo;  

but should be
e = Sx + (a/W) * Eo;    

  //Need to use slope relative to the road cross slope not the horizontal
        //See example 4-9a problem 2 HEC-22 pg 4-49

**Comment by cbuahin** [comment]
Addressed in #134
