### ISSUE TITLE
A number of issues in lidproc.c

### ISSUE THREAD

**Issue by jlhomme** [USEPA/Stormwater-Management-Model#116]
(1) The engine allows a Biocell to have no Storage layer (ie `storageThickness == 0`), although the GUI prevents that.
However the `SurfaceInfil` is not capped correctly in this situation (`storageThickness == 0` and `soilTheta >= soilPorosity`), leading to mass balance issues.
This had been raised a while ago by Mike Gregory [here](https://www.openswmm.org/Topic/5454/lid-storage-layer).
I believe the `else if` should be replaced by a `if` in `biocellFluxRates()`.

From [biocellFluxRates()](https://www.openswmm.org/SWMM523/lidproc-c/biocellFluxRates?HighlightLines=74-75) in lidproc.c (SWMM5.2.3)
```
    //... storage & soil layers are full
    else if ( soilTheta >= soilPorosity && storageDepth >= storageThickness )
```
This fix gives more sensible infiltration results and improves the water balance, when using the engine independently from the GUI.

(2) Missing brackets in trenchFluxRates

From [trenchFluxRates()](https://www.openswmm.org/SWMM523/lidproc-c/trenchFluxRates?HighlightLines=79-81) in lidproc.c (SWMM5.2.3)

```
    // ... find net fluxes for each layer
    f[SURF] = SurfaceInflow - SurfaceEvap - StorageInflow - SurfaceOutflow /
              theLidProc->surface.voidFrac;;
```
It should be
```
    // ... find net fluxes for each layer
    f[SURF] = (SurfaceInflow - SurfaceEvap - StorageInflow - SurfaceOutflow) /
              theLidProc->surface.voidFrac;;
```

(3) Missing lines in pavementFluxRates
I have found that in my experience this line is needed to limit the pavement outflow when 'storage & soil layers are full'.
`PavePerc = MIN(PavePerc, SoilPerc);`

From [pavementFluxRates()](https://www.openswmm.org/SWMM523/lidproc-c/pavementFluxRates?HighlightLines=139-161) in lidproc.c (SWMM5.2.3)

```
    //... storage & soil layers are full
    else if ( soilThickness > 0.0 &&
              storageDepth >= storageThickness &&
              soilTheta >= soilPorosity )
    {
        //... soil perc can't exceed storage outflow
        maxRate = StorageDrain + StorageExfil;
        if ( SoilPerc > maxRate ) SoilPerc = maxRate;
 
        //... storage outflow can't exceed soil perc
        else
        {
            //... use up available exfiltration capacity first
            StorageExfil = MIN(StorageExfil, SoilPerc);
            StorageDrain = SoilPerc - StorageExfil;
        }

        // <<<<< here is where the extra line should go <<<<<<<<<<<<<
 
        //... limit surface infil. by available pavement volume
        availVolume = (paveThickness - paveDepth) * paveVoidFrac;
        maxRate = availVolume / Tstep + PavePerc + PaveEvap;
        SurfaceInfil = MIN(SurfaceInfil, maxRate);
    }
```

Also I have found that it is necessary to cap Storage Exfil when 'soil and pavement layers are full'.

From [pavementFluxRates()](https://www.openswmm.org/SWMM523/lidproc-c/pavementFluxRates?HighlightLines=162-170) in lidproc.c (SWMM5.2.3)
```
    //... soil and pavement layers are full
    else if ( soilThickness > 0.0 &&
              paveDepth >= paveThickness &&
              soilTheta >= soilPorosity )
    {
        PavePerc = MIN(PavePerc, SoilPerc);
        SoilPerc = PavePerc;
        SurfaceInfil = MIN(SurfaceInfil,PavePerc);

        // start suggested lines <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	maxRate = MAX(StorageVolume / Tstep + SoilPerc - StorageEvap, 0.0);
	StorageExfil = MIN(StorageExfil, maxRate);
        // end suggested lines <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    }
```

(4) Logic issue in getStorageDrainRate
If the LID has both a Soil layer and a Paving layer, `head` can get added the `paveDepth` twice, and the `surfaceDepth` is not always added correctly.
To be consistent with the code comments, I suggest to change the 2nd `if` into a `else if`, and to rewrite `if ( paveThickness > 0.0 ) head += paveDepth;` as follows (although I appreciate there are several ways to fix this):
```
	if (paveThickness > 0.0)
	{
		head += paveDepth;
		if (paveDepth >= paveThickness)	head += surfaceDepth;
	}
	else
	{
		head += surfaceDepth;
	}
```

From [getStorageDrainRate()](https://www.openswmm.org/SWMM523/lidproc-c/getStorageDrainRate?HighlightLines=28-54) in lidproc.c (SWMM5.2.3)

```
        // --- a soil layer exists
        if ( soilThickness > 0.0 )
        {
            // --- increase head by fraction of soil layer saturated
            if ( soilTheta > soilFieldCap )
            {
                head += (soilTheta - soilFieldCap) /
                        (soilPorosity - soilFieldCap) * soilThickness;
 
                // --- soil layer is saturated, increase head by water
                //     depth in layer above it
                if ( soilTheta >= soilPorosity )
                {
                    if ( paveThickness > 0.0 ) head += paveDepth;        //<<<<< this line needs rewriting <<<<<
                    else head += surfaceDepth;
                }
            }
        }
 
        // --- no soil layer so increase head by water level in pavement
        //     layer and possibly surface layer
        if ( paveThickness > 0.0 )                        //<<<<< change into else if <<<<<
        {
            head += paveDepth;
            if ( paveDepth >= paveThickness ) head += surfaceDepth;
        }
    }
```

**Comment by cbuahin** [comment]
Addressed in #134
