### ISSUE TITLE
Compiler warning: unreferenced local variable in findNodeDepths

### ISSUE THREAD

**Issue by jlhomme** [USEPA/Stormwater-Management-Model#117]
I'm certain other people are aware of this, but I haven't seen an existing Issue for that, so I am logging this.

Compiler warning (in Visual Studio 2019): unreferenced local variable in findNodeDepths
`Warning	C4101	'yOld': unreferenced local variable`

From [findNodeDepths()](https://www.openswmm.org/SWMM523/dynwave-c/findNodeDepths?HighlightLines=9-17) in dynwave.c (SWMM5.2.3)

```
    int i;
    double yOld;        // previous node depth (ft)
 
    // --- compute outfall depths based on flow in connecting link
    for ( i = 0; i < Nobjects[LINK]; i++ ) link_setOutfallDepth(i);
 

    yOld = 0.0;    //<<<<< initialise yOld, to remove compiler warning when compiling with OMP support.

    // --- compute new depth for all non-outfall nodes and determine if
    //     depth change from previous iteration is below tolerance
#pragma omp parallel num_threads(NumThreads)
```

**Comment by cbuahin** [comment]
Addressed in PR #134 .
