### ISSUE TITLE
Upgrades to speed

### ISSUE THREAD

**Issue by swmm-js** [USEPA/Stormwater-Management-Model#118]
My internal testing shows some large speed improvements at a cost of about 0.1% error. I'm sure I'm doing something wrong, I'll finish up the basics of the full web interface and then do some more testing on EPA-SWMM. Thanks for pointing me in the right direction.

**Comment by dickinsonre** [comment]
You probably need to add some details on the speed improvements so others can verity your findings.

**Comment by swmm-js** [comment]
I will, these are unit tests on large amounts of randomized data using currently ugly optimizations and my absolutely awful implementations of memos in c. They aren't in my codebase yet, but it looks promising, if 0.05%-0.09% errors don't compound too much.

**Comment by michaeltryby** [comment]
@swmm-js Thanks for reaching out. I look forward to reopening this issue once you have more information to share.
