### ISSUE TITLE
In the new SWMM 5.1.013 code there is a new parameter (extIfaceInflow;) in struct ExtInflow that does not get used 

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/Stormwater-Management-Model#12]
In the new SWMM 5.1.013 code there is a new parameter (extIfaceInflow;) in struct ExtInflow that does not get used or is always set to 0.  Is this for a future or deprecated change?

//------------------------------
// DIRECT EXTERNAL INFLOW OBJECT
//------------------------------
struct ExtInflow
{
   int            param;         // pollutant index (flow = -1)
   int            type;          // CONCEN or MASS
   int            tSeries;       // index of inflow time series
   int            basePat;       // baseline time pattern
   double         cFactor;       // units conversion factor for mass inflow
   double         baseline;      // constant baseline value
   double         sFactor;       // time series scaling factor
   double         extIfaceInflow;// external interfacing inflow   ???  Set to zero and never updated
   struct ExtInflow* next;       // pointer to next inflow data object
};
typedef struct ExtInflow TExtInflow;

**Comment by bemcdonnell** [comment]
@dickinsonre, this is for the API for generating node inflow. This and a few other pieces of OWA’s code were introduced in 5.1.13. Nearly all the surgical changes I made Everything except toolkitAPI.c/.h

**Comment by bemcdonnell** [comment]
So to answer the question: yes, it is going to stick around :-)

**Comment by dickinsonre** [comment]
Thanks All, I suspected that was the answer @bemcdonnell
