### ISSUE TITLE
Incorrect conduit capacity being reported

### ISSUE THREAD

**Issue by LRossman** [USEPA/Stormwater-Management-Model#122]
The conduit capacity being reported as output at each reporting step is incorrect. It is actually the conduit's Manning friction slope which was meant to be a temporary replacement during the development of release 5.2.3 but was never set back to report capacity. The simple fix is to remove line 712,  `c = getSF(j, fabs(q), y);` from link.c.

**Comment by LRossman** [comment]
I need to explain what's going on here. The line of code I referred to previously and the `getSF ` function it calls does not appear in either the current develop branch nor the source code for v.5.2.3 released to the EPA SWMM web site. However the 5.2.3 engine DLL posted to the latter is reporting friction slope instead of conduit capacity in its output time series. It appears the posted DLL was generated using a version of link.c that contained the line of code in question. So the bug persists in the engine DLL but not in the current source code. Rebuilding the engine using the v5.2.3 code in this repository (is that what is currently in the master branch?) should fix the issue.

**Comment by michaeltryby** [comment]
@LRossman Yes, v5.2.3 is checked into master.

**Comment by LRossman** [comment]
Yes, it affects all types of links.

**Comment by cbuahin** [comment]
@LRossman, could you confirm that this issue has been addressed in 5.2.4?

**Comment by cbuahin** [comment]
I know it was addressed in the GitHub version 5.2.3 but was not updated on the official EPA website. I just want to make sure it is addressed in the new release.

**Comment by LRossman** [comment]
Yes, it's addressed in the new release.

**Comment by cbuahin** [comment]
Addressed in #134
