### ISSUE TITLE
Culvert design equations ( besides FHWA)

### ISSUE THREAD

**Issue by WindingWinter** [USEPA/Stormwater-Management-Model#132]
This is just a general idea.

Refer to this post [here](https://www.openswmm.org/Topic/33772/culvert-design-in-epa-swmm).

It seems that EPA SWMM is using FHWA culvert equations. But this is purely a US standard.

Any plans to support other country's standard like the UK? Or even better, allow the user to specify their own culvert equation?

**Comment by cbuahin** [comment]
Unfortunately, there is no immediate plan to support other standards. You could attempt to incorporate it into the code for your own purposes.

**Comment by dickinsonre** [comment]
If I am not mistaken this was an idea first posted on OpenSWMM.ORG
