### ISSUE TITLE
Pollutant surface runoff mass not matching wet weather inflow mass

### ISSUE THREAD

**Issue by LRossman** [USEPA/Stormwater-Management-Model#133]
The total pollutant mass from subcatchment washoff shown in SWMM's Status Report will sometimes be significantly greater than the reported wet weather mass inflow to the conveyance system, especially for longer duration simulations. The reason for this is that SWMM sets the runoff concentration to 0 when runoff flow is below 0.001 in/hr, AFTER rather than before it computes the runoff mass loading. Thus when it adds up pollutant mass inflow to conveyance nodes it will not count any mass from low runoff time steps which were counted when adding up subcatchment washoff loads. Hence the discrepancy.

The fix is to set low runoff pollutant concentration to 0 before rather than after the washoff load is computed for mass balance purposes in file surfqual.c

NOTE: The reason runoff concentration is set to 0 for low runoff flow is that SWMM reports such flow as 0 so it would look strange if a non-zero concentration was associated with a zero flow.

**Comment by dickinsonre** [comment]
Interesting, thank you Lew Rossman.
