### ISSUE TITLE
Access violation in module swmm_open

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#14]
Access violation exception occurs when there are LID controls, but no subcatchments in the model.

LidProcs is not initialized in lid_create() method if number of subcatchments is zero:

void lid_create(int lidCount, int subcatchCount)
{
    LidProcs = NULL;
    LidGroups = NULL;
    LidCount = lidCount;

    //... create LID groups
    GroupCount = subcatchCount;
    if ( GroupCount == 0 ) return;
    ...

**Comment by michaeltryby** [comment]
Closed in Release v5.1.14
