### ISSUE TITLE
How to generate hotstart file using pyswmm

### ISSUE THREAD

**Issue by gourikadam** [USEPA/Stormwater-Management-Model#141]
Hello,
I wish to generate hotstart file after every single day simulation, in the continuous simulation.  Can anyone guide me regarding, how to generate a hotstart file while  running the simulation using pyswmm

Thank you
Regards,
Gouri

**Comment by bemcdonnell** [comment]
@cbuahin or @michaeltryby do either of you have authority to pass this issue to the pyswmm project ?

**Comment by cbuahin** [comment]
@bemcdonnell, while we are able to do transfer issues within agency related projects, we are unable to transfer to projects outside the agency. I would suggest that @gourikadam recreate this  issue on the pyswmm repo.

**Comment by gourikadam** [comment]
Thank you. As suggested will move this issue to pyswmm repo.
