### ISSUE TITLE
Add a TERSE option to SKIP_STEADY_STATE setting

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/Stormwater-Management-Model#155]
When a user implements SKIP_STEADY_STATE either via steady-state flow conditions or using the EVENTS feature, the model outputs long stretches of constant outputs for its hydraulics that are not of interest during post-processing. Adding a TERSE option would eliminate output during these periods, which could yield substantial savings in output file sizes and thus post-processing times.

A suggested syntax for SKIP_STEADY_STATE is shown below. I submitted coded for this to EPA in 2015. It was quite simple to code at the time.

• NO – no change from EPA SWMM – calculations are performed at all timesteps, and all requested output is saved at each reporting timestep.

• YES – follows the method in EPA SWMM unless an [EVENTS] section is present in the input file. If [EVENTS] are specified, then routing calculations are only performed on specified dates, with constant flows in conduits (from last dynamic simulation step) during intervening steady-state conditions.

• VERBOSE – identical to YES

• TERSE – same as YES/VERBOSE except that no output is written to the binary output file during steady-state.

**Comment by cbuahin** [comment]
@MitchHeineman, I would suggest converting this issue into a discussion for now to allow others to chime in. One of the things are considering is to use HDF5 as another option for saving SWMM output. This format will give us greater flexibility and transparency to handle the case you are highlighting. The format is self documenting and open so vendors and the SWMM community might find it more workable.

**Comment by MitchHeineman** [comment]
I rewrote this as a discussion topic.
