### ISSUE TITLE
Rain Barrel LID - covered option increases runoff continuity error

### ISSUE THREAD

**Issue by NandanaPerera** [USEPA/Stormwater-Management-Model#166]
When covered option is checked for rain barrel LID, it creates a runoff continuity error. This can be significant depending on the relative area of the rain barrel footprint area.
Rain falls on the barrel does not enter it because of the lid, but that volume is not currently accounted.
To avoid this, the rainfall volume on the footprint of the rain barrel may be routed directly to the subcatchment outlet or the pervious area (if available).

**Comment by cbuahin** [comment]
I am leaving a reminder here to change the documentation to reflect this fix.
