### ISSUE TITLE
Unexpected Abnormal Value at Simulation Start When RoutingStep Equals ReportStep

### ISSUE THREAD

**Issue by wsy-00** [USEPA/Stormwater-Management-Model#181]
Hello,
I've encountered an unusual behavior in SWMM version 5.2 and 5.1 that does not appear in version 5.0. Specifically, when the RoutingStep is set to the same value as the ReportStep, the simulation begins with an extremely large and unexpected value. This anomaly occurs immediately at the start of the simulation. However, if I set the RoutingStep to be slightly smaller than the ReportStep, the issue does not occur, and the simulation runs as expected.

- RoutingStep = ReportStep = 30s

Version 5.1:
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/60472366/d0ff5c85-04ca-41f0-8a03-cfb2224b995e)
Version 5.2:
![bd0d898dcf0a4438c30ba6d43264f43](https://github.com/USEPA/Stormwater-Management-Model/assets/60472366/e89fa657-6a6f-4e41-907d-c3efdeb4f0e3)
Version 5.0:
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/60472366/8fe49a15-5a53-40cf-b9a7-3c284ac8bf4b)

- RoutingStep = 20s, ReportStep = 30s
Version 5.2:
![image](https://github.com/USEPA/Stormwater-Management-Model/assets/60472366/b5f1531a-3655-4b0e-9821-d16266011bb7)

 I am wondering if anyone else has experienced this problem or can offer any insights into why this might be happening.
Thank you for your assistance.

**Comment by cbuahin** [comment]
@wsy-00, Thank you for reaching out with this issue. There have been several fixes since version 5.0 that may be responsible for what you are observing. Without additional details, it is difficult to pinpoint exactly what might be causing your observation.  First, what type of routing method are you using? Are you using the kinematic wave or dynamic wave approach? If you are using dynamic wave, are you using the variable time-step option? If yes, what options are you using? Have you reviewed the report file and is your model converging with reasonable mass balance errors? Better still, are you in position to share your model if it is small enough to share?

My initial guess is that the initial spurious spike you are seeing is a result of the model not converging at the start of the simulation. What happens if you keep the same time step for reporting and routing but reduce both of them to say 5 seconds?

**Comment by wsy-00** [comment]
@cbuahin Thank you for your response! 
I apologize for not being able to share the model directly. If the information I've provided so far is insufficient, I can extract parts of the model later. Interestingly, when I set RoutingStep=ReportStep=5s, no issues occurred. Similarly, no issues arose when I set RoutingStep=29s and ReportStep=30s. I have attached the status reports for different simulation settings at the end, which should include all the configuration details. If there is anything unclear, please let me know. In fact, while debugging the source code, I found that the actual step length is always equal to MinRoutingStep in the first step and to RoutingStep in the second step. Therefore, it is puzzling to me that setting it to 29s did not cause any issues.
Thank you again for your attention!
[Routingstep5s.txt](https://github.com/user-attachments/files/16042669/Routingstep5s.txt)
[Routingstep29s.txt](https://github.com/user-attachments/files/16042670/Routingstep29s.txt)
[Routingstep30s.txt](https://github.com/user-attachments/files/16042671/Routingstep30s.txt)

**Comment by cbuahin** [comment]
The report files you have shared seem to confirm my suspicion. If you look at the Routing Time Step Summary section, you will see that the timesteps are different and the 30-second simulation yields a larger mass balance error that could explain the spurious initial blip you see at the beginning. At the beginning of the simulation, where presumably there is no flow or the flow is small, the courant condition that limits the timestep will be bounded on the upper end by 30 seconds versus the 29 seconds. While seemingly small, you may be right on the cusp of where it is significant enough to lead to the increased mass balance errors you see. One test you could try is to increase the maximum number of iterations to see if you are able to achieve 100% convergence and the do your comparison again.

To conclude, it seems to me you have a solution to the problem. Unless there is a significance to the 30 second timestep, it makes sense to just reduce it.

While we strive to ensure the results for SWMM are consistent with each release, addressing bugs and adding new features inevitably lead to slight changes and hopefully improved results. We try ensure that these major updates occur only on minor or major releases and not on patches.

**Comment by cbuahin** [comment]
@wsy-00, I plan to close this issue unless you have additional questions.

**Comment by wsy-00** [comment]
@cbuahin Sure! Thank you again!
