### ISSUE TITLE
Cannot use more than 512 timeseries files

### ISSUE THREAD

**Issue by SimonDelmas** [USEPA/Stormwater-Management-Model#197]
The time series files are all opened at the start of execution and closed when execution ends (`swmm_open()` and `project_close()`).
I have a project with a lot of boundary conditions and RTC defined an I hit the maximum number of open file hard limit ([details here](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmaxstdio?view=msvc-170)).

These files don't need to remain open during program execution, and closing them once they've been read will correct my problem.

**Comment by LRossman** [comment]
The maximum number of open files was set to 8192 in version 5.2.0 (see line 268 in swmm5.c).

**Comment by SimonDelmas** [comment]
Thanks for your quick reply, Indeed, I'm still on version 5.1... I'm going to upgrade.
I close this issue.
