### ISSUE TITLE
Where to Post Bug Fixes

### ISSUE THREAD

**Issue by LRossman** [USEPA/Stormwater-Management-Model#22]
I have updated the v5.1.013 source files to fix all of the bugs identified to date. They appear in the attached zip file along with a set of examples for each bug fix. It appears that this repo is strictly archival and doesn't allow branches cloned off of the master to be published. Is the OWA-SWMM repo the place to push these bug fixes? If so, will they find their way into an official EPA-SWMM release anytime soon?
[swmm5.1.013_Bug_Fixes.zip](https://github.com/USEPA/Stormwater-Management-Model/files/3277395/swmm5.1.013_Bug_Fixes.zip)

**Comment by dickinsonre** [comment]
Thanks @LRossman

**Comment by bemcdonnell** [comment]
@LRossman, I hope I'm not being presumptuous with this idea but it feels like there is an active development community around OWA-SWMM more than any other place.  How do you and other community members feel about branching off `master` at OWA-SWMM and submitting the PR of bug fixes into that? Else, it is also reasonable to post them into EPA-SWMM's page, then I can merge/mesh them down into OWA-SWMM.  I think this topic merits a larger discussion with the communit(y/ies).  What are your thoughts?

**Comment by LRossman** [comment]
@bemcdonnell I just tried to publish a branch I created off of `develop` in the OWA-SWMM repo with the bug fixes in it but GitHub said I did not have permission to access the repo.

**Comment by bemcdonnell** [comment]
@lrossman, let me fix that. I’ll update the permissions today!
