### ISSUE TITLE
Units conversion issue in Curve number infiltration

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#25]
In infile.c infil_getInfil() method:

      case CURVE_NUMBER:
        depth += runon / tstep;
        return curvenum_getInfil(&CNInfil[j], tstep, rainfall, depth);

runon is in ft/sec. To convert it to depth, it should be depth+=runon*tstep.

**Comment by dickinsonre** [comment]
Is this depth used only for reporting?

**Comment by LRossman** [comment]
Fixed in release 5.1.015.
