### ISSUE TITLE
High runoff continuity error caused by LID

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#28]
SoilVolume is not initialized for roof disconnection LID, so SoilVolume from other LID could be added to roof disconnection LID thus causes high runoff continuity error.

void roofFluxRates(double x[], double f[])
{
......
    SurfaceVolume = surfaceDepth;
	**SoilVolume = 0;  // This line should be added to reset SoilVolume**
    SurfaceInfil = 0.0;
......
}

This simple model below illustrates the issue. Run it directly, the runoff error is around -24% and Final Storage at roof disconnection LID is 88.01 mm (much large than its depth at 1). Delete the other LID usage and run again, the runoff continuity error will drop down to normal value.

[test.txt](https://github.com/USEPA/Stormwater-Management-Model/files/3654352/test.txt)

I also discovered total volume comprises four parts (lidproc_saveResults() method):
    totalVolume = SurfaceVolume + PaveVolume + SoilVolume + StorageVolume;

The PaveVolume is only initialized in pavementFluxRates() method, which could potentially used for other LID unit. How about initialize the four variables in  lidproc_getOutflow() method:

    //... initialize layer flux rates and moisture limits
  **SurfaceVolume = 0.0;
  PaveVolume = 0.0;
  SoilVolume =0.0;
  StorageVolume = 0.0;**
    SurfaceInflow  = inflow;
    SurfaceInfil   = 0.0;

**Comment by dickinsonre** [comment]
Thanks @Tiehong   this looks like a good finding,

**Comment by LRossman** [comment]
Fixed in Release 5.1.014.
