### ISSUE TITLE
Update swmm to recognize relative paths to auxiliary data files 

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/Stormwater-Management-Model#29]
Sometimes when running swmm on an input file that references auxiliary data (such as rainfall data), the simulation fails because it is unable to open the auxiliary file (ERROR 317). This is because auxiliary files either have to be referenced using an absolute path or the input and auxiliary files must reside in the current working directory. This can be inconvenient in many situations. 

It would be more user friendly if auxiliary data files could also be referenced using paths relative to the location of the input file itself. This way absolute paths in the input file could be avoided and the user would have the flexibility to choose a working directory that suites the task they are performing. For example, batch processing input files for optimization, uncertainty analysis, or testing purposes.

**Comment by michaeltryby** [comment]
The CRT library contains many functions for file handling and directory control that could be used to implement this functionality.

**Comment by LRossman** [comment]
I believe this issue has been addressed in release 5.2.0. From the epaswmm5_updates.txt file:
_6 . Support for relative path names for files appearing in an input file has been added making these files more portable._

**Comment by michaeltryby** [comment]
For sure! Thanks Lew!
