### ISSUE TITLE
Exception in reporting average results

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#30]
If the "Report average results" option is chosen and the number of links does not equal to the number of nodes in the model, an "Access violation in module swmm_step at step 62, hour 0 --- execution halted." exception will happen.

In output_saveAvgResults() method:

	for (i = 0; i < **Nobjects[NODE]**; i++)
	{
		SysResults[SYS_STORAGE] += (REAL4)(Link[i].newVolume * UCF(VOLUME));
	}

Nobjects[NODE] should be Nobjects[LINK].

**Comment by dickinsonre** [comment]
This seems similar to a bug Lew Rossman logged about the SWMM5 GUI on openswmm.org  I cannot seem to find it right now.

**Comment by LRossman** [comment]
Fixed in Release 5.1.014.
