### ISSUE TITLE
Missing 0 in Version Folder Names

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/Stormwater-Management-Model#4]
My apologies if this is a silly request but can the folders named such as 5.1.10 be renamed 5.1.010? to fill in the missing 0 in the release name?

**Comment by michaeltryby** [comment]
@dickinsonre We are changing over to symantic versioning convention for numbering SWMM releases. You can read about it here: http://semver.org/

**Comment by dickinsonre** [comment]
Thanks, very much for the information, Michael.
