### ISSUE TITLE
Control action not reported for curve controlled action

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#40]
In control.c executeActionList() method, the following code 
                if ( RptFlags.controls )
is changed to
                if ( RptFlags.controls && a1->curve < 0                        //(5.1.011)
                     && a1->tseries < 0 && a1->attribute != r_PID )            //(5.1.011)

This change will cause curve/timeseries action not reported in the report file.

Please see attached sample input file.

[TeardropPark_ModulatedOrifice_ControlCurve03.zip](https://github.com/USEPA/Stormwater-Management-Model/files/4429072/TeardropPark_ModulatedOrifice_ControlCurve03.zip)

**Comment by bemcdonnell** [comment]
@Tiehong, for big models run for long periods with lots of control points this will add an enormous amount of lines to a report file.  There will be a value for every routing time step for every link controlled by PID/TS/Curve.  If it's a Timeseries you know the settings in advance, if it is a curve, you can figure out the input and reverse engineer the settings.  PID is the only one that you wouldn't really be able to untangle.  I'd be worried about increasing the size of the RPT file :-)

**Comment by dickinsonre** [comment]
The code Lew Rossman has only sends a line to the report file if the value of the control setting has changed.  It might be worthwhile to show when a new Target value is set as well.  There will not be volumes of new lines.  You can do the same with curves and time series.  Only show changes and not the intermediate values.

**Comment by cbuahin** [comment]
@dickinsonre , is this not information that could be retrieved from capacity timeseries in the results file? Modifying the engine to record the first instance of a target setting being changed may introduce extraneous tracking infrastructure and complexity into the code.

**Comment by dickinsonre** [comment]
Yes, it can be found from the capacity data.  I will say that i have experimented with the control action report and it can get really big.

**Comment by cbuahin** [comment]
I am going to propose we close this issue for now unless anyone has a reservation.
