### ISSUE TITLE
NetCDF Output Format

### ISSUE THREAD

**Issue by cbuahin** [USEPA/Stormwater-Management-Model#41]
Would there be any interest in using the NetCDF as the output file format for SWMM? It is self documenting, portable, and is able to scale well.

**Comment by dickinsonre** [comment]
Of course, someone(s) will have to do this https://www.unidata.ucar.edu/software/netcdf/ test it, explain it, document it and make it backward compatible with the existing inp format.  The advantage of the existing inp format is you can see it and save it in a form people in the future can use.

**Comment by cbuahin** [comment]
@dickinsonre, my proposal is only to write the output (i.e., *.out) in NetCDF. The input file (i.e., *.inp) will remain unchanged. I can implement it and share it for consideration.

**Comment by michaeltryby** [comment]
Hey @cbuahin, This is a good a place as any to discuss things :smile: 

NetCDF sounds promising! I had been toying with the idea of a HDF5 binary output writer: 
https://www.hdfgroup.org/solutions/hdf5/

I believe HDF5 is the underlying format used for pandas data frames. It would be pretty cool to generate a SWMM output file in a format directly accessible from pandas! It would give Python users complete unfettered access to their SWMM simulation results.  

We could program this feature to be modular, so it could potentially support multiple output formats - classic, HDF5, NETCDF, ..., eventually something even better. Then the user could chose the best format for their particular application.

**Comment by MattAndersonPE** [comment]
XMDF as a solution for Extensile Model Data Format (
https://apps.dtic.mil/dtic/tr/fulltext/u2/a461368.pdf) should be
considered.   It uses HDF5 as the format and compression.
https://en.wikipedia.org/wiki/XMDF#cite_note-1

**Comment by cbuahin** [comment]
This will be integrated into future planning efforts.
