### ISSUE TITLE
#define SOL     /* Compile as a shared object library */

### ISSUE THREAD

**Issue by jmpmcmanus** [USEPA/Stormwater-Management-Model#5]
I have not been able to compile swmm5 as a shared object file, on a linux (fedora) system. I have been able to compile it as an executable, by commenting out the references to Windows in swmm5.c and uncommenting #define CLE. However, if I try the same thing with #define SOL I get the following error:

/usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:12: swmm5] Error 1

There are no reference to SOL further down in swmm5.c. What do I have to do to get this option to work?

Thanks
Jim

**Comment by bemcdonnell** [comment]
@jmpmcmanus, I copied this issue over to OpenWaterAnalytics/Stormwater-Management-Model#74
