### ISSUE TITLE
String concatenation in the report file.

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#57]
If a node has very large total inflow, the value will be concatenated with the previous value and make it hard for other application to parse the line (see example below). It will be better if a space was added between the values.

  `*******************`
  Node Inflow Summary
  `*******************`
  
  `-------------------------------------------------------------------------------------------------`
`                                  Maximum  Maximum                  Lateral       Total        Flow`
`                                  Lateral    Total  Time of Max      Inflow      Inflow     Balance`
`                                   Inflow   Inflow   Occurrence      Volume      Volume       Error`
  `Node                 Type           CMS      CMS  days hr:min    10^6 ltr    10^6 ltr     Percent`
  `-------------------------------------------------------------------------------------------------`
  J10                  JUNCTION     0.000169677.750     0  01:20           0    1.49e+06      -0.001

**Comment by LRossman** [comment]
Fixed in Release 5.1.015.
