### ISSUE TITLE
Possible race condition in dynwave.c

### ISSUE THREAD

**Issue by LRossman** [USEPA/Stormwater-Management-Model#58]
There is a possible race condition in the multi-threaded portion of the `findNodeDepths `function in `dynwave.c`. The variable `converged`, defined outside of the parallel loop, can be changed within the loop. The fix is to remove `converged ` from the parallel loop and set its value later by checking each `Xnode[i].converged` value until the first `FALSE `value is found.

**Comment by dickinsonre** [comment]
Thanks, Lew.  I wonder if the user should have an option to compute the link flow even if the number of iterations is over 2 and the link is considered converged.  Having better testing models now it might be informative to see if there is a lot of speed up using the convergence scheme or if the answers diverge for larger networks.

**Comment by LRossman** [comment]
This issue has been resolved in PR #56 .
