### ISSUE TITLE
ImportError: libswmm-output not found.

### ISSUE THREAD

**Issue by CAIJUNYI** [USEPA/Stormwater-Management-Model#6]
When I use the package `swmm_reader` in `tools`, it raises the import error about libswmm-output. I wonder what is the libswmm-output, and where I can get it?

**Comment by CAIJUNYI** [comment]
Thx. I am looking forward to it. It is a great job for our python programmers.

**Comment by michaeltryby** [comment]
@CAIJUNYI The source for libswmm-output is in `swmm-output`. You need to build the library and include it in the `swmm-reader` package for it to work. Like @bemcdonnell said, I am currently working on the next version of these packages to make them more friendly for python users.
