### ISSUE TITLE
File open issue

### ISSUE THREAD

**Issue by Tiehong** [USEPA/Stormwater-Management-Model#68]
If a model contains more than 508 time series that have external files, the engine will throw "ERROR 361" even these files are all valid. This seems to be a limitation in C run time. According to Microsoft Docs:

C run-time I/O now supports up to 8,192 files open simultaneously at the low I/O level. This level includes files opened and accessed using the _open, _read, and _write family of I/O functions. By default, up to 512 files can be open simultaneously at the stream I/O level. This level includes files opened and accessed using the fopen, fgetc, and fputc family of functions. The limit of 512 open files at the stream I/O level can be increased to a maximum of 8,192 by use of the _setmaxstdio function.

if I add _setmaxstdio(8192); before project_open(), the model will run:

	_setmaxstdio(8192);

        // --- open a SWMM project
        project_open(f1, f2, f3);

**Comment by dickinsonre** [comment]
Wow, that is a nice finding @Tiehong I remember various MidWest SWMM5 users had this issue.

**Comment by michaeltryby** [comment]
@Tiehong This is really interesting ... Modern data analytics applications are engineered to manipulate data in memory. Perhaps we could think about moving SWMM processing of time series in that direction.

**Comment by LRossman** [comment]
To avoid the file limit we could use the same approach as is currently done for preprocessing rainfall data files, namely write the contents of each time series file one by one to a single scratch binary file which is then used to retrieve individual time series values during the simulation (the start position of each time series is saved to an internal array of indexes). You could probably do something similar using a [memory stream](https://www.codeproject.com/Articles/808776/Cplusplus-Simplistic-Binary-Streams) approach as well.

**Comment by michaeltryby** [comment]
Closed in Release #5.2.0
