### ISSUE TITLE
Time step averaging issue

### ISSUE THREAD

**Issue by shanninio-jing** [USEPA/Stormwater-Management-Model#71]
When the SWMM engine announced that we will be able to get time series results for a project's nodes and  links reported as average values computed over a reporting time step instead of being interpolated point values at the end of the reporting time step.

While we were testing the latest SWMM engine so that we can switch our engines; we potentially found a bug in the averaging of reported values for pipes. This bug may not impact systems that do not  experience frequent flow reversals.

Here is the brief description of the issue. 
While averaging the values the absolute values of the flow are used for averaging instead of the flows with the associated flow direction (negative value for flow reversal). After the flow is averaged, the last timesteps flow direction is assumed to the flow direction for the whole averaged period. If the flow changes direction from upstream to downstream and from downstream to upstream, during the averaging period, then the averaging will overestimate the flow and potentially the effective flow direction; this will also lead to issues with volume calculations.

 [https://www.openswmm.org/SWMM51015/output-c/output_updateAvgResults](url)
![swmm](https://user-images.githubusercontent.com/18667657/112158888-faa38680-8bbe-11eb-959b-543778559562.PNG)

While we are on the topic we would like to take the opportunity to mention an item on the wish list. Would it be possible for the user to define how the averaging is being performed the three options that we can think of are the following. 
1.	Centralized average: The values on both sides (before and after the reported timestep) of reported timestep are equally averaged. (averaged and assigned to the middle timestep)  
2.	Left averaging: Values after(in time) the reported timestep  are averaged and assigned. (averaged and assigned to the first timestep)  
3.	Right averaging: Values before(in time) the reported timestep  are averaged and assigned. (averaged and assigned to the last timestep)

We've posted this issue to the SWMM listserv as well. As always we are thankful for the development team in supporting SWMM and releasing updated engines frequently.

**Comment by michaeltryby** [comment]
Closed in Release v5.2.0
