### ISSUE TITLE
Context for the table  Most Frequent Nonconverging Nodes in SWMM 5.2

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/Stormwater-Management-Model#81]
The table  Most Frequent Nonconverging Nodes is a great addition as it helps user identifuy problem simulation areas of the network but it lacks context.  If a node does not converge 10 percent of the time how many times is is not converging.  I suggest adding the number of time steps to the summary time step routing table so the user can get some context.  It tells you the number or report steps, the number actual steps per report step and the total time steps.

Here is an example

  *********************************
  **Most Frequent Nonconverging Nodes**
  *********************************
  Node 10208 (35.59%)
  Node 82309 (32.86%)
  Node 80608 (12.74%)
  Node 80408 (10.31%)
  Node 81009 (9.00%)

  
  *************************
  Routing Time Step Summary
  *************************
  Minimum Time Step           :    19.13 sec
  Average Time Step           :    29.12 sec
  Maximum Time Step           :    60.00 sec
  % of Time in Steady State   :     0.00
  Average Iterations per Step :     5.10
  **% of Steps Not Converging   :    35.59
  % Number of Report Steps    :      989
  % Total TS / Report TS      :    29.12
  % Total Time Steps (TS)     :    28799**
  Time Step Frequencies       :
     60.000 - 23.031 sec      :    42.81 %
     23.031 -  8.841 sec      :    57.19 %
      8.841 -  3.393 sec      :     0.00 %
      3.393 -  1.303 sec      :     0.00 %
      1.303 -  0.500 sec      :     0.00 %

Here is the code for report.c - just adding three lines to the Routing Time Step Summary using known information.

void report_writeTimeStepStats(TTimeStepStats* timeStepStats)
//
//  Input:   timeStepStats = routing time step statistics
//  Output:  none
//  Purpose: writes routing time step statistics to report file.
//
{
    double timeStepCount = timeStepStats->timeStepCount;
    double totalRoutingTime;      // time taken for all flow routing steps
    double fSteadyState = 0.0;    // fraction of reporting time in steady state
 
    if ( Nobjects[LINK] == 0 || timeStepStats->timeStepCount == 0.0 )
        return;

    totalRoutingTime = timeStepStats->steadyStateTime + timeStepStats->routingTime;
    if (totalRoutingTime > 0.0)
        fSteadyState = 100.0 * timeStepStats->steadyStateTime / totalRoutingTime;

    WRITE("");
    WRITE("*************************");
    WRITE("Routing Time Step Summary");
    WRITE("*************************");
    fprintf(Frpt.file,
        "\n  Minimum Time Step           :  %7.2f sec",
        timeStepStats->minTimeStep);
    fprintf(Frpt.file,
        "\n  Average Time Step           :  %7.2f sec",
        timeStepStats->routingTime / timeStepCount);
    fprintf(Frpt.file,
        "\n  Maximum Time Step           :  %7.2f sec",
        timeStepStats->maxTimeStep);
    fprintf(Frpt.file,
        "\n  %% of Time in Steady State   :  %7.2f", MIN(fSteadyState, 100.0));
    fprintf(Frpt.file,
        "\n  Average Iterations per Step :  %7.2f",
        timeStepStats->trialsCount / timeStepCount);
    fprintf(Frpt.file,
        "\n  %% of Steps Not Converging   :  %7.2f",
        100.0 * (double)NonConvergeCount / timeStepCount);
    fprintf(Frpt.file,
        "\n  %% Number of Report Steps    :%9.0f",  timeStepCount);   // RED_2022
    fprintf(Frpt.file,
        "\n  %% Total TS / Report TS      :  %7.2f", timeStepStats->routingTime/ timeStepCount); // RED_2022
    fprintf(Frpt.file,
        "\n  %% Total Time Steps (TS)     :%9.0f", timeStepStats->routingTime);   // RED_2022

**Comment by michaeltryby** [comment]
Closed in Release v5.2.0
