### ISSUE TITLE
Compiling issue on OS X

### ISSUE THREAD

**Issue by kristianfoerster** [USEPA/Stormwater-Management-Model#84]
Compiling on OS X using gcc via cmake failed due to errors in output.c

Left: fix that works, right: original

![changes_to_output](https://user-images.githubusercontent.com/17268463/169457903-91e8e412-4bc3-405f-be21-39e3f9fd4c54.png)

**Comment by timcera** [comment]
Thank you!  The edits work for Linux also.

**Comment by cbuahin** [comment]
This issue should be addressed in #131 .
