### ISSUE TITLE
Possible bad area approximation for shallow water depths in egg shaped conduits?

### ISSUE THREAD

**Issue by MatthiasSchilder** [USEPA/Stormwater-Management-Model#85]
Until now, my assumption was that the Phillips Standard Egg shape SWMM uses and the German egg profile according to DIN4263  are equivalent. At least in the case of full filling, the assumption seems to be correct. 

However, in the case of very shallow water depths (< 0.1 * shape height), they seem to behave differently. I tracked this down to the second and third value in A_Egg from xsect.dat. Compared to my german reference book, those two values overestimate the area at depth / full depth = 0.04 and 0.08 by about 30% (relative). For higher fill levels, the deviation is around 0. This deviation propagates to the calculation of the velocity, where I observed it first.
```
static const double A_Egg[N_A_Egg] =
{.0000,.0150,.0400,.0550,.0850,.1200,.1555,.1900,.2250,.2750,
 .3200,.3700,.4200,.4700,.5150,.5700,.6200,.6800,.7300,.7800, 
 .8350,.8850,.9250,.9550,.9800,1.000};
```

My table says:
```

+--------------------+---------------------------+------------------------------+------+
| depth / full depth | area / full area SWMM egg | area / full area DIN4263 egg |  Δ%  |
+--------------------+---------------------------+------------------------------+------+
|               0,04 |                     0,015 |                       0,0116 | 29,3 |
|               0,08 |                      0,04 |                       0,0316 | 26,6 |
|               0,12 |                     0,055 |                       0,0562 | -2,1 |
|               0,16 |                     0,085 |                       0,0849 |  0,1 |
|                0,2 |                      0,12 |                       0,1173 |  2,3 |
|               0,24 |                    0,1555 |                       0,1531 |  1,6 |
|               0,28 |                      0,19 |                       0,1917 | -0,9 |
|               0,32 |                     0,225 |                       0,2331 | -3,5 |
|               0,36 |                     0,275 |                       0,2767 | -0,6 |
|                0,4 |                      0,32 |                       0,3223 | -0,7 |
|               0,44 |                      0,37 |                       0,3697 |  0,1 |
|               0,48 |                      0,42 |                       0,4186 |  0,3 |
|               0,52 |                      0,47 |                       0,4686 |  0,3 |
|               0,56 |                     0,515 |                       0,5196 | -0,9 |
|                0,6 |                      0,57 |                       0,5712 | -0,2 |
|               0,64 |                      0,62 |                       0,6233 | -0,5 |
|               0,68 |                      0,68 |                       0,6755 |  0,7 |
|               0,72 |                      0,73 |                       0,7274 |  0,4 |
|               0,76 |                      0,78 |                       0,7784 |  0,2 |
|                0,8 |                     0,835 |                       0,8275 |  0,9 |
|               0,84 |                     0,885 |                       0,8738 |  1,3 |
|               0,88 |                     0,925 |                       0,9163 |  0,9 |
|               0,92 |                     0,955 |                       0,9535 |  0,2 |
|               0,96 |                      0,98 |                       0,9833 | -0,3 |
+--------------------+---------------------------+------------------------------+------+


```
(from: Hydraulik der Abwasserkanäle in der Praxis (Pecher/Schmidt/Pecher, 1991)

Could you give me a hint where I can find information on how Phillips Standard Egg shapes are geometrically constructed and where those values in the lookup tables might come frome, so I might check my assumption?

**Comment by dickinsonre** [comment]
The Egg Shape links were in the original Transport block of SWMM1 and later added to Extran in the late 1970's  Any documentation will be in the SWMM4 code and the original EPA Documents for SWMM1 from 1971.  

SWMM5 does not report the velocity if the depth is small - see this link https://www.openswmm.org/Topic/31660/low-flow-zero-velocity

**Comment by MatthiasSchilder** [comment]
A velocity != 0 is reported, With water depth 0.164 ft and full height 3.9 ft in my MWE, SWMM is calculating the area from those deviating (according to my ref) first values in the lookup table, which then influence the reported velocity.

**Comment by dickinsonre** [comment]
I have the original code and will check the values.  I do seem to remember the Egg shaped links were for Boston

**Comment by LRossman** [comment]
The German Egg profile appears to be the same as the Phillips Standard Egg shape as pictured in Figure 6-4 of the Storm Water Management Model User's Manual Version II (EPA-670/2-75-017, March 1975). It is also the same as the egg-shaped sewer section shown in Figure 3-17 of Wastewater Engineering by Metcalf & Eddy Inc. (McGraw-Hill, 1972). The A-egg table in SWMM 5 was taken from the table used in both SWMM III and SWMM 4 which in turn appeared in the 1982 report "Stormwater Management Model User's Manual Version III Addendum I EXTRAN" by L.A. Roesner et al., Camp Dresser & McKee, Inc.

I used the dimensions shown on the German Egg profile (as well as the one in Metcalf & Eddy) to compute by hand the relative area at a relative depth of 0.04. My result was 0.0316, the same as in the German table and different from SWMM's 0.04 value.

It seems like the Egg area table should be corrected (and the hydraulic radius table should be checked as well).

**Comment by LRossman** [comment]
As a follow up to my previous comment, the corrected geometric properties for small relative depths for an Egg shaped sewer are as follows (found by using analytical formulas for the circular lower portion of the shape):

|Y/Yfull | A/Afull  | R / Rfull | W / Wmax |
|-----| ------| ---- | ----|
| 0.04 | 0.0116 | 0.130 | 0.325|
| 0.08 | 0.0316 | 0.244 | 0.427 |

whereas the old values were:

|Y/Yfull | A/Afull  | R / Rfull | W / Wmax |
|-----| ------| ---- | ----|
| 0.04 | 0.015 | 0.097 | 0.298|
| 0.08 | 0.040 | 0.216 | 0.433 |

**Comment by michaeltryby** [comment]
@LRossman are you going to include this in v5.2.1 patch?

**Comment by LRossman** [comment]
Yes. I will push the revised xsect.dat file to my `lew-develop` branch shortly.

**Comment by MatthiasSchilder** [comment]
@LRossman Thank you for adressing this issue so quickly.

**Comment by michaeltryby** [comment]
That’s fantastic! Thanks Lew!

**Comment by MatthiasSchilder** [comment]
Because one of my users needs the fix in a timely manner, I took the liberty of checking in the change and creating a PR. I would be happy if the change is considered for the next release.

**Comment by LRossman** [comment]
@MatthiasSchilder the Egg geometry correction was added to version 5.2.1 which was released last week to the [EPA SWMM web page](https://www.epa.gov/water-research/storm-water-management-model-swmm). It includes the full source code which can also be found in the `lew-develop` branch of this repo.

**Comment by MatthiasSchilder** [comment]
Sorry, I managed to overlook this.
