### ISSUE TITLE
Could not initialize taskbar when running in Citrix

### ISSUE THREAD

**Issue by pitheway** [USEPA/Stormwater-Management-Model#94]
When launching the app in Citrix as published application getting the error Could not initialize taskbar. Error:-2147467263. It works when launched in full desktop mode. Is this something that would be difficult to get around?

**Comment by LRossman** [comment]
I'm not a Citrix user so this is just a stab in the dark, but release 5.2.1 added the display of a progress indicator into the program’s task bar icon while a simulation is running. So I wonder if that could be the cause of the error. Is it possible to load an earlier version of SWMM into Citrix and see if the error still occurs.

**Comment by pitheway** [comment]
I would love to try older ver. Do you know where I can download it?
